nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: mixed

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin
    - windows

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard